ALTER SCHEMA `ti-actors`  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;
ALTER SCHEMA `ti-authentication`  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;
ALTER SCHEMA `ti-settings`  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;
ALTER SCHEMA `sys` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;
